### PR TITLE
Enhanced the Budget UI and Added a Overlay/Popover for the table

### PR DESCRIPTION
**Pull request by wilke0818**
- Added some extra styling to make the overall page look a bit nicer

- Created an Overlay and Popover that triggers first when hovering over the table to see the instructions and then when a row is clicked, some information regarding the number of people lacking that resource is shown

TODOs:
- Better incorporate this UI functionality. Better information can probably be shown rather than just the number of people lacking certain characteristics
- Combine the clicking of the table with Amy's circles that way they highlight when different traits are selected
Screen Shot 2020-01-31 at 11 34 12 AM
Screen Shot 2020-01-31 at 11 34 39 AM

### CODE REVIEW

**Review by ryaanahmed — CHANGES_REQUESTED** [review]
This is good, but right now the interaction is super hidden. Can you have the instructional popover visible all the time, instead of just when the user mouses over? And then I'd leave the popover showing the combined data up as well, once you click.

**Comment by wilke0818** [comment]
Added back the Popover, but moved it into its own column for now. I'll probably add styling it and putting it in a better spot into the issue I have open for the UI

**Comment by wilke0818** [comment]
@ryaanahmed Ready for review
Added back the Popover, but moved it into its own column for now. I'll probably add styling it and putting it in a better spot into the issue I have open for the UI
Screen Shot 2020-01-31 at 4 31 07 PM
Screen Shot 2020-01-31 at 4 31 15 PM

**Review by ryaanahmed — APPROVED** [review]
Great, thanks for the changes! This feels a lot more usable for now. 

Have you made an issue for the follow-on improvements that you suggested in the PR message?

**Comment by wilke0818** [comment]
Yes, under #35

**Comment by ryaanahmed** [comment]
great, thanks.

**Pull request merged**
