### PR TITLE
Campaign - sectioned into rounds and final results page

### PR DESCRIPTION
**Pull request by amy-lei**
- Refactored citizens from budget and campaign game into single component in campaignView.js (not sure if this was the optimal place to put it)
- Hardened game through less priority points and different counting system
- Sectioned game into three rounds 
    - Between each round, user receives feedback through a sample population
    - On the third submission, user is redirected to results page where there is a table, map, and sample population
- Hovering over citizen gives a less robotic description (e.g. "I am (not) satisfied with the candidate's stance on...")

image
image
image

### CODE REVIEW

**Comment by mscuthbert** [comment]
Can a citizen be satisfied with some stances but not others?

**Comment by amy-lei** [comment]
> Can a citizen be satisfied with some stances but not others?

@mscuthbert 
Do you mean to show both sides? Like to include the stances the citizen was unsatisfied with on top of the satisfied ones?

Right now, the code only shows one or the other based on how the citizen voted, but not both. If the citizen will support, then all of the stances that met their preference/threshold are listed. Similarly, if the citizen did not support, then all of the stances that failed to match their preference are listed. We thought this would provide hints in both directions and explain why some citizens voted while others didn't.

**Comment by ryaanahmed** [comment]
This is HUGE progress in the right direction. I think @mscuthbert's comment is right on -- would be worth showing that even citizens who voted YAY have some preferences unfulfilled, and vice-versa.

I'd suggest that moving forward we split the adjustment and feedback into two views. That way we can have a richer view of the survey data. Something like this:

Untitled

**Comment by ryaanahmed** [comment]
Right now, the model makes the game reasonable well-tuned in difficulty for South Africa, but playing in Kenya or Botswana is too easy. We may need to tune thresholds individually.

**Comment by ryaanahmed** [comment]
I also really really think we should cut some of the parameters. It's too many to hold in your head and understand what's going on. I'd suggest 4-6, tops.

**Review by ryaanahmed — APPROVED** [review]
HUGE progress -- this is definitely a step in the right direction.

I'm requesting changes only because it seems that

**Comment by ryaanahmed** [comment]
Also: I wonder if we shouldn't show the sample set from the full country by default as feedback -- it makes things too easy. Might be good to reserve that until the results view.

**Comment by amy-lei** [comment]
@ryaanahmed separating the feedback from the adjustment sounds like a good idea. we can work on that next. 

i believe ben and felix have already cut down on the parameters but just didn't make a PR yet

**Comment by ryaanahmed** [comment]
@amy-lei great! This is really taking shape.

**Pull request merged**
