### PR TITLE
Map Quiz

### PR DESCRIPTION
**Pull request by meesuekim**
still need to comment and fix a few bugs, but it is currently a functioning map quiz.

### CODE REVIEW

**Comment by maoivy** [comment]
We fixed the bug where you could guess a country twice in a row and also added the country list. Some future steps to take are 1) formatting the UI to look nicer and 2) greying out names of countries the user has already guessed correctly.

**Review by ryaanahmed — CHANGES_REQUESTED** [review]
Looks good -- needs additional documentation, but we can save that for an additional PR by the end of tomorrow, as I'd like to get this merged into the main codebase ASAP.

Just got a failing frontend test -- @maoivy @meesuekim @bengao01 -- if someone could quickly fix that, I can merge. (@ me when ready.)

**Comment by meesuekim** [comment]
@ryaanahmed  map_quiz.test.js was trying to import from a MapQuizD3, which doesn't exist, so I changed it to import from map_quiz_svg

**Comment by ryaanahmed** [comment]
> @ryaanahmed map_quiz.test.js was trying to import from a MapQuizD3, which doesn't exist, so I changed it to import from map_quiz_svg

thanks -- looks good to merge now, so going ahead.

**Review by ryaanahmed — APPROVED** [review]

**Pull request merged**
